Feature#5 리스트 수정
ggosunnae/ggosunnae_front pull request #33
Opened 2024-08-01 13:13 UTC by radiant0922

## #️⃣연관된 이슈

> ex) #5 

## 📝작업 내용

>
 react-slick link 오류 해결,
라우터 수정 후 link 경로 변경,
 header 정리, 
 infotoggle 컴포넌트 수정,

### 스크린샷 (선택)
header 파일 중복되는 거 정리하는데
![image](https://github.com/user-attachments/assets/20bd5fe4-a76d-44bc-9d1e-e15847f9c345)
이 부분은 src\components\Layout\Header.tsx 여기에 
![image](https://github.com/user-attachments/assets/4c1d15c5-add3-4cc3-8bee-5383dc1f57cb)
이 부분은 src\components\Common\AppBar.tsx 여기에 
코드가 길어질까봐  따로 작업했는데
합치는 게 나을까요 이대로 분리하는게 나을까요?

2024-08-01 13:30 UTC, Banal972 requested changes
onToggle쪽 수정이 필요할것 같습니다

2024-08-01 13:30 UTC, Banal972 commented on src/components/Common/InfoToggle.tsx
onChange 나 onClick 함수를 넣을 수 있도록 수정해주세요

2024-08-01 14:15 UTC, radiant0922 commented on src/components/Common/InfoToggle.tsx
onChange함수 넣을 수 있게 수정했습니다!

2024-08-04 10:07 UTC, Banal972 approved these changes
onChange 넣은거 확인 했습니다
추후에 컴포넌트 interface 수정이 있을수도 있을것 같아서
제가 따로 수정하게 된다면 말씀드릴게요

2024-08-06 11:28 UTC, merged